#!/usr/bin/python3

import googletrans
import sys
import argparse
import os

def get_config():
	with open('config', 'r') as f:
		lines = f.read().splitlines()

	cfg = {}
	for line in lines:
		if line.startswith('#') or line.startswith('['):
			continue
		data = line.split()
		if '=' in data and len(data) == 3:
			cfg[data[0]] = data[2]

	return cfg

def get_lang(res):
	lang = []
	src = res.src
	dst = res.dest
	if src in googletrans.LANGUAGES:
		lang.append(googletrans.LANGUAGES[src])
		lang.append(src)
	else:
		lang.append(src)
		lang.append(googletrans.LANGCODES[src])

	if dst in googletrans.LANGUAGES:
		lang.append(googletrans.LANGUAGES[dst])
		lang.append(dst)
	else:
		lang.append(dst)
		lang.append(googletrans.LANGCODES[dst])

	return lang

def detect_lang(args):
	det = trans.detect(args.text)
	print("[Confidence] {}%".format(det.confidence*100))
	if det.lang in googletrans.LANGUAGES:
		print("[Language]   {} [{}]".format(googletrans.LANGUAGES[det.lang].capitalize(), det.lang))
	else:
		print("[Language]   {} [{}]".format(det.lang.capitalize(), googletrans.LANGCODES[det.lang]))
	sys.exit(0)

def trans_file(trans, args):
	fn = args.text

	if os.path.isfile(fn):
		with open(fn, 'r') as f:
			lines = f.read().splitlines()
			for line in lines:
				translate_text(trans, args, data=line)
	else:
		print(f"Error: {fn} no such file found")
		sys.exit(1)

def translate_text(trans, args, data=None):
	cfg = get_config()
	verbose = []
	dst = 'en'

	if data:
		text = data
	else:
		text = args.text

	if args.dst:
		dst = args.dst
	else:
		if 'dst' in cfg:
			dst = cfg['dst']
		else:
			verbose.append('Default "dst" not found in config, using "en"')

	if dst in googletrans.LANGUAGES or args.dst in googletrans.LANGCODES:
		dest = dst
	else:
		print(f"Error: {dst} is not present in supported languages.")
		sys.exit(1)

	if args.src:
		if args.src in googletrans.LANGUAGES or src in googletrans.LANGCODES:
			res = trans.translate(text, src=args.src, dest=dest)
		else:
			print(f"Error: {args.src} is not present in supported languages")
			sys.exit(1)
	else:
		res = trans.translate(text, dest=dest)
	

	if args.v or ('v' in cfg and cfg['v'] == 'True'):
		lang = get_lang(res)
		verbose.append("{}[{}] => {}[{}]".format(lang[0], lang[1], lang[2], lang[3]))
		for vb in verbose:
			print(vb)

	if args.out:
		if args.p or ('p' in cfg and cfg['p'] == 'True'):
			print("[TEXT] {}".format(res.text), file=open(args.out, 'a'))
			print("[PRON] {}".format(res.pronunciation), file=open(args.out, 'a'))
		else:
			print("{}".format(res.text), file=open(args.out, 'a'))
	else:
		if args.p or ('p' in cfg and cfg['p'] == 'True'):
			print("[TEXT] {}".format(res.text))
			print("[PRON] {}".format(res.pronunciation))
		else:
			print("{}".format(res.text))

def main(trans, args):

	if args.file:
		trans_file(trans, args)

	if args.detect:
		detect_lang(args)

	translate_text(trans, args)


if __name__ == '__main__':
	parser = argparse.ArgumentParser(
		description="Translate text from one language to another language",
		epilog="Note: This script uses 'googletrans' for translation of text")
	parser.add_argument('text', help='The text to be translated/Name of the file to be read')
	parser.add_argument('-p', help='Show pronunciation in English (en)', action='store_true', default=False)
	parser.add_argument('-v', help='Display more data', action='store_true', default=False)
	parser.add_argument('--detect', help='Detect the language (with confidence)', action='store_true', default=False)
	parser.add_argument('--src', help='Use this as the source language')
	parser.add_argument('--dst', help='Translate text to the given language (lang code / lang name)')
	parser.add_argument('--out', help='Use this file as output to store translated data')
	parser.add_argument('--file', help='Use this file as input to translate', action='store_true', default=False)
	args = parser.parse_args()

	trans = googletrans.Translator()
	main(trans, args)